Get all response pages for Shelly.GetComponents
home-assistant-libs/aioshelly pull request #722
Opened 2024-11-25 12:08 UTC by bieniu

2024-11-25 13:22 UTC, chemelli74 requested changes

2024-11-25 13:22 UTC, chemelli74 commented on aioshelly/rpc_device/device.py
> +        while len(first_page["components"]) < total and counter < MAX_ITERATIONS:
```suggestion
        while len(first_page["components"]) < total and counter <= MAX_ITERATIONS:
```

2024-11-27 11:38 UTC, chemelli74 commented
I think the approach is fine.

2024-12-17 17:58 UTC, chemelli74 approved these changes

2024-12-31 13:29 UTC, thecode approved these changes

2025-01-09 16:20 UTC, merged