Improve logging
home-assistant-libs/aioshelly pull request #84
Opened 2021-03-27 16:22 UTC by chemelli74

2021-03-27 16:56 UTC, bieniu approved these changes
LGTM 👍

2021-03-28 06:55 UTC, thecode requested changes

2021-03-28 06:55 UTC, thecode commented on aioshelly/coap.py
> +            _LOGGER.debug("Adding CoAP message to subscriptions for device %s", msg.ip)
```suggestion
            _LOGGER.debug("Calling CoAP message update for device %s", msg.ip)
```
This is not adding the message, but it is calling the update handler subscribed at `subscribe_updates`

2021-03-28 06:55 UTC, thecode commented on aioshelly/coap.py
> +        _LOGGER.debug("Adding CoAP message to subscriptions for device %s", ip)
```suggestion
        _LOGGER.debug("Adding device %s to CoAP message subscriptions", ip)
```

2021-03-28 12:08 UTC, thecode approved these changes

2021-03-28 12:08 UTC, merged